config/routes.rb
Rails.application.routes.draw do
  resources :events
  root 'main#index'

  get 'about' => 'main#about'
  # get 'calendar' => 'main#events'
  get 'contact' => 'main#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord


    def end_time_as_str
        end_time.present? ? end_time.stamp("Jan 1, 2017") : "TBD" 
    end

    def start_time_as_str
        start_time.present? ? start_time.stamp("Jan 1, 2017") : "TBD" 
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @admin = true
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :location, :start_time, :end_time, :price, :description)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/events/_form.html.erb
<div class="light narrowed">
  <%= simple_form_for(@event) do |f| %>
    <%#= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :location %>
      <%= f.input :start_time, as: :date, html5: true %>
      <%= f.input :end_time, as: :date, html5: true %>
      <%= f.input :price %>
      <%= f.input :description %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% if @admin %>
<%= link_to 'New Event', new_event_path %>
<hr>
<% end %>

<h1 class="page-header">
  EVENTS
</h1>
<%= month_calendar events: @events do |date, events| %>
 
  <%= date %>

  <% events.each do |event| %>
    <div class="event-title">
      <%= link_to event.name, event %>
    </div>
  <% end %>
<% end %>

<hr>

<table class="table table-hover table-bordered light">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Price</th>
      <th>Description</th>
      <% if @admin %>
      <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event %></td>
        <td><%= event.location %></td>
        <td><%= event.start_time_as_str %></td>
        <td><%= event.end_time_as_str %></td>
        <td><%= event.price %></td>
        <td><%= event.description %></td>
        <% if @admin %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="text-left"><%= link_to 'Back', events_path, class: "btn btn-default" %></div>

<div class="light">

<h1 class="page-header text-center">
  <%= @event.name .present? ? @event.name.upcase : "TBD"%>
</h1>
<p>
  <strong>WHERE:</strong> &nbsp; <%= @event.location.present? ? @event.location : "TBD" %>
</p>

<p>
  <strong>WHEN:</strong>
  <%= @event.start_time_as_str %> - <%= @event.end_time_as_str %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price.present? ? number_to_currency(@event.price) : "TBD" %>
</p>

<div class="desc">
  <%= @event.description.present? ? @event.description : "No description available." %>
</div>
<% if @admin %>
<%= link_to 'Edit', edit_event_path(@event) %>
<% end %>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Lorain County Music Foundation</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><%= link_to "Events", events_path %></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Admin</li>
                <li><a href="#">One more separated link</a></li>
            </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'music.png' %>
    <title>Lorain County Music Foundation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container-fluid" id="main-content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/about.html.erb
<div class="light">
    <h2 class='page-header'>About Lorain County Music Foundation</h2>
    <div class="">
        <ul>
            <li>Lorain Count Muisc Founation wishes to provide an outlet for local aspiring & established musicians of all ages, genres & experience levels to perform in a safe & positive environment.</li>
            <li>Our ultimate goal is to establish a children’s day camp that would provide music therapy for underprivileged & special needs children in the area</li>
            <li>In addition to creating a day camp for kids, we plan to begin a program with the local high schools & colleges to help students to earn school credit <br>
                by volunteering & doing something they love...all while building their skills & finishing their degree.</li>
        </ul>
    </div>
</div>

app/views/main/contact.html.erb
<h1 class="page-header">Contact Us!</h1>

<div class="contact-list">
<h2>LCMF Board Memebers</h2>
<ul class="list-unstyled contact-list">
    <li class="contact-list-item"><span class="role">PRESIDENT & FOUNDER: </span> <span class="name pull-right"> GERI R. CIACCHI </span></li>
    <li class="contact-list-item"><span class="role">VICE PRESIDENT: </span> <span class="name pull-right">JORDAN LUCIA </span></li>
    <li class="contact-list-item"><span class="role">DIRECTOR & TREASURER: </span> <span class="name pull-right">JOSEPH J. ROCHA</span></li>
    <li class="contact-list-item"><span class="role">SECRETARY: </span> <span class="name pull-right">BRITTANY HICKS </span></li>
    <li class="contact-list-item"><span class="role">DOCUMENTARIAN:</span> <span class="name pull-right"> BOB BOLEY </span></li>
    <li class="contact-list-item"><span class="role">MEDIA:</span> <span class="name pull-right"> J.L. THOMAS </span></li>
    <li class="contact-list-item"><span class="role">HEAD OF SECURITY & STAFF:</span> <span class="name pull-right"> JOE CEH </span></li>
    <li class="contact-list-item"><span class="role">COOK CRAFTERY:</span> <span class="name pull-right"> KRISTA SMITH </span></li>
    <li class="contact-list-item"><span class="role">FIRST AID RESPONDERS:</span> <span class="name pull-right"> JESS PAULEY & ALEXANDER KEEFE </span></li>
    <li class="contact-list-item"><span class="role">STAGE: </span> <span class="name pull-right">JACK LUGAS, ADAM HALL, BOB BOLEY, & JORDAN LUCIA</span></li>
    <li class="contact-list-item"></li>
    <li class="contact-list-item"><span class="role">STAFF:</span>
        <span class="">BELINDA WARREN & FAMILY, 
            CHRISSY GORDAN, 
            TONY JOHNS, 
            NICOLE JOHNS, 
            EMILY LEGGIT, 
            ERICA
            & MORE. 
        </span>

</ul>

</div>
<hr>
<p>: 
<br>

app/views/main/index.html.erb
<div class="row">
    <div class="text-center light">
        <h1 class="page-header">Lorain County Music Foundation</h1>
        <p>LCMF wishes to provide an outlet for local aspiring & established musicians of all ages, genres & experience levels to perform in a safe & positive environment. 
        Our ultimate goal is to establish a children’s day camp that would provide music therapy for underprivileged & special needs children in the area
        In addition to creating a day camp for kids, we plan to begin a program with the local high schools & colleges to help students to earn school credit by volunteering  & doing something they love…all while building their skills & finishing their degree.
        </p>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-md-12 text-center">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active text-center">
                <%= image_tag("music-heart.jpg") %>
                <div class="carousel-caption">
                    <h3>Lorain County Music Foundation</h3>
                </div>
            </div>
            <div class="item text-center">
                <%= image_tag("kid1.jpg") %>
                <div class="carousel-caption">
                    <h3>Our goal is to create a music camp for kids!!!</h3>
                </div>
            </div>
            <div class="item">
                <%= image_tag("kid1.jpg") %>
                <div class="carousel-caption">
                    <h3>Our goal is to create a music camp for kids!!!</h3>
                </div>
            </div>
        </div>

        </div>

    </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>